[package]
name = "Malware_Rhapsody"
version = "0.0.1"
edition = "2021"
authors = ["Evgeney Knyazhev (SarK0Y) <sark0y@protonmail.com>"]
license = "free"
readme = "README.md"
repository = "https://github.com/SarK0Y/Malware_Rhapsody"
description = "Small researching of Linux's security for fun and education.. don't be silly to use it in wild. Have a great day, Dear Researcher/Scholar 💯❤️"
crate_type = ["staticlib"]
keywords = ["research", "education", "malware", "simple", "fun"]
categories = ["research", "security", "command-line-utilities"]
[dependencies]
chrono = "0.4.31"
substring = "1.4.5"
num-traits = "0.2.17"
libc = "0.2.152" #"0.2.149"
#once_cell = "1.19.0"
dirs = "5.0.1"
[features]
#default=["dbg0"]
in_dbg =[]
dbg0=[]
